In [22]:
%pip install pandas
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.1.0)
Requirement already satisfied: numpy>=1.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
file_path = "grapheme-color-trials-2023-09-12-13-36-11_test_1.csv"
df = pd.read_csv(file_path)

In [24]:
#print(df.to_string())

# Get the list of all column names from headers
column_headers = list(df.columns.values)
print("The Column Header :", column_headers)
df.info()

The Column Header : ['id', 'battery_id', 'start_r', 'start_g', 'start_b', 'r', 'g', 'b', 'datetimenow', 'inducer_id', 'stimulus', 'synesthesia_test_id', 'test_name', 'email']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   108 non-null    int64
 1   battery_id           108 non-null    int64
 2   start_r              108 non-null    int64
 3   start_g              108 non-null    int64
 4   start_b              108 non-null    int64
 5   r                    108 non-null    int64
 6   g                    108 non-null    int64
 7   b                    108 non-null    int64
 8   datetimenow          108 non-null    object
 9   inducer_id           108 non-null    int64
 10  stimulus             108 non-null    object
 11  synesthesia_test_id  108 non-null    int64
 12  test_name            108 non-null    object
 13  email                108 non-null    object
dtypes: int64(10), object(4)
memory usage: 11.9+ KB

In [25]:
rgb_test = df[['r', 'g', 'b', 'stimulus']]
rgb_vals = df[['r', 'g', 'b']]
df

,id,battery_id,start_r,start_g,start_b,r,g,b,datetimenow,inducer_id,stimulus,synesthesia_test_id,test_name,email
0,14214651,229126,231,237,212,231,237,212,2023-09-07 13:32:51,32,6,1444747,grapheme-color,jacobh.inquiries@gmail.com
1,14214652,229126,188,47,197,188,47,197,2023-09-07 13:32:52,25,Z,1444747,grapheme-color,jacobh.inquiries@gmail.com
2,14214653,229126,166,177,195,166,177,195,2023-09-07 13:32:52,1,B,1444747,grapheme-color,jacobh.inquiries@gmail.com
3,14214654,229126,208,73,24,208,73,24,2023-09-07 13:32:52,20,U,1444747,grapheme-color,jacobh.inquiries@gmail.com
4,14214655,229126,205,180,161,205,180,161,2023-09-07 13:32:52,29,3,1444747,grapheme-color,jacobh.inquiries@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,14214754,229126,158,165,120,158,165,120,2023-09-07 13:33:10,26,0,1444747,grapheme-color,jacobh.inquiries@gmail.com
104,14214755,229126,101,124,231,101,124,231,2023-09-07 13:33:10,22,W,1444747,grapheme-color,jacobh.inquiries@gmail.com
105,14214756,229126,137,46,131,137,46,131,2023-09-07 13:33:10,18,S,1444747,grapheme-color,jacobh.inquiries@gmail.com
106,14214757,229126,236,58,109,236,58,109,2023-09-07 13:33:10,26,0,1444747,grapheme-color,jacobh.inquiries@gmail.com
107,14214758,229126,73,242,181,73,242,181,2023-09-07 13:33:10,26,0,1444747,grapheme-color,jacobh.inquiries@gmail.com

In [26]:
stim_rgb = rgb_test.groupby('stimulus')

In [27]:
import pandas as pd

# Assuming you have a DataFrame named 'rgb_test' with a 'stimulus' column
# and you want to iterate over each unique 'stimulus' value

# Group the DataFrame by 'stimulus'
grouped = rgb_test.groupby('stimulus', as_index=True)
#grouped2 = rgb_vals.groupby('stimulus')
#print(grouped)
for group_name, group_data in grouped:
    print(f"Group: {group_name}")
    print(group_data)
    stim = grouped.get_group(group_name)

def rgb_calc_test(dataset):
# Iterate over each unique 'stimulus' value
    rgb_list = []
    for stimulus_value, group_data in grouped:
        stim = grouped.get_group(stimulus_value)
       # 
        print(stim)
    
        #print(group_data)
        
        
        rgb1 = stim.iloc[0]
        print(rgb1)
        rgb2 = stim.iloc[1]
        rgb3 = stim.iloc[2]
  
        rgb_diff = abs(rgb1 - rgb2) + abs(rgb2 - rgb3) + abs(rgb3 - rgb1)
        rgb_diff.append(rgb_list)
        #print(rgb_diff)
    return rgb_list
        #print(f"Stimulus Value: {stimulus_value}")
        #print(f"Mean Value: {mean_value}")

Group: 0
       r    g    b stimulus
103  158  165  120        0
106  236   58  109        0
107   73  242  181        0
Group: 1
      r    g    b stimulus
13  153    1  177        1
46   14   47  109        1
48   90  199   39        1
Group: 2
      r    g    b stimulus
66  197  143  179        2
85  196  104  216        2
92   61  127   26        2
Group: 3
      r    g    b stimulus
4   205  180  161        3
6   227   40   70        3
75  208  191  232        3
Group: 4
      r    g    b stimulus
12  132  176   88        4
54  187   79    4        4
69   84   78  100        4
Group: 5
      r    g    b stimulus
45   86   80  170        5
47  139  137  207        5
93   96   18  193        5
Group: 6
      r    g    b stimulus
0   231  237  212        6
15  152  118  205        6
52   79  124  255        6
Group: 7
      r    g    b stimulus
23  105   33   17        7
27  200  192  111        7
88   54  185   84        7
Group: 8
      r    g    b stimulus
30  125   12   59        8
33  145  247  158        8
84   20  156   37        8
Group: 9
      r    g    b stimulus
16   20  142  169        9
38  200  151   95        9
58   91   71   63        9
Group: A
      r    g    b stimulus
36  213    2  162        A
53   22   57  135        A
81   99  158    9        A
Group: B
      r    g    b stimulus
2   166  177  195        B
25   39  165  172        B
39  183  250   40        B
Group: C
      r    g    b stimulus
37  142  157  213        C
56   70  201  161        C
63  150   22  224        C
Group: D
     r    g    b stimulus
26  99   84  242        D
67  90  120  108        D
77  80  109  247        D
Group: E
      r    g    b stimulus
28  138  240  222        E
80  187   46  146        E
97    1  125  143        E
Group: F
     r    g    b stimulus
40  29  202  251        F
49  97  189   60        F
91  75  248  217        F
Group: G
     r    g    b stimulus
31  13   64   43        G
78  71   76   34        G
98   9  177  207        G
Group: H
       r    g    b stimulus
8    101  139   92        H
24   176   69  207        H
101  243  103   56        H
Group: I
      r   g    b stimulus
5   241  76  208        I
14  216  55  152        I
19  232  45   38        I
Group: J
      r    g    b stimulus
18  121  178   21        J
20   60  170   32        J
89   70  130  227        J
Group: K
      r    g    b stimulus
44  216  117   60        K
55   47  103  168        K
86  123   46  233        K
Group: L
      r    g    b stimulus
60  197   60   36        L
79  212  112  108        L
87  126   65   76        L
Group: M
       r    g    b stimulus
90    32  212  205        M
95    20  151   94        M
100  137  243  167        M
Group: N
     r    g    b stimulus
35  54  179  238        N
50  37   51  219        N
73  22  163  110        N
Group: O
       r    g    b stimulus
11   252  245  183        O
59   119  130  205        O
102  110   46  108        O
Group: P
      r    g    b stimulus
21  222  202  169        P
70   74  110  154        P
74   68   43   18        P
Group: Q
      r    g    b stimulus
57  198   31   44        Q
61   46  210  187        Q
83  237  246   26        Q
Group: R
      r    g    b stimulus
17   23  126   28        R
62  124  156   34        R
99   66   68  254        R
Group: S
       r    g    b stimulus
32     3  210   24        S
64   219   50  105        S
105  137   46  131        S
Group: T
     r    g    b stimulus
9   99   60   49        T
42  27  252  100        T
68  64  168   15        T
Group: U
      r    g    b stimulus
3   208   73   24        U
7     6   56   80        U
65  100  164  126        U
Group: V
      r    g    b stimulus
10   13   13  184        V
29  250  223  118        V
94   75  182  150        V
Group: W
       r    g    b stimulus
51   166  149   65        W
71   157  215   78        W
104  101  124  231        W
Group: X
      r    g    b stimulus
43   56  162    8        X
72  113  225  247        X
82    8  140  161        X
Group: Y
     r    g    b stimulus
34  63  125  245        Y
41  48   64  114        Y
96  63  245   41        Y
Group: Z
      r    g    b stimulus
1   188   47  197        Z
22  139   70  118        Z
76  117  166   96        Z

In [28]:
#total_participant_name = 'sub_02_score'
#stim = 'stimulus'
#total_column = total_rgb_value(total_participant_name, stim)
#print(total_column)
#pd.Series([total_column], name=total_participant_name)
#df['sub_02_score']
#result = grouped.apply(total_rgb_value(total_participant_name, stim))
#print(total_column)
#for i in len(stim_rgb['stimulus']):
#test = rgb_calc_test(stim_rgb)
#print(test.shape)
#print('hello??')

def rgb_diff(group):

    
    rgb1 = group[['r', 'g', 'b']].nth(0)
    rgb2 = group[['r', 'g', 'b']].nth(1)
    rgb3 = group[['r', 'g', 'b']].nth(2)
    rgb_diff = abs(rgb1 - rgb2) + abs(rgb2 - rgb3) + abs(rgb3 - rgb1)

    return rgb_diff

In [29]:
import pandas as pd

#Sample DataFrame with 'stimulus', 'R', 'G', and 'B' columns
#stim must be string, ie letters
#takes in (3,3) RGB values for each stimulus
#gives back (3,) rgb values for each stimulus (A-Z, 0-9)
def total_rgb_value(test_participant_name, stim):
# Group by 'stimulus'
    grouped = rgb_test.groupby([stim], as_index=False)

#measures the difference in RGB values
    for stimulus_value, group_data in grouped:
        stim = grouped.get_group(stimulus_value)
        #print(stim)


        # Select only the RGB columns for calculations
        rgb_data = stim[['r', 'g', 'b']]

        # Calculate RGB differences
        rgb_diff = abs(rgb_data.iloc[0] - rgb_data.iloc[1]) + abs(rgb_data.iloc[1] - rgb_data.iloc[2]) + abs(rgb_data.iloc[2] - rgb_data.iloc[0])
        
        #the value is also divided by 255 to normalize the data. (it reflects a ratio between RGB values)
        rgb_diff_norm = rgb_diff / 255
        
   # print(f"stimulus value: {stimulus_value} \n group data: {group_data}\n grouped: {grouped} \n rgb diff: {rgb_diff}")
    # Add the new Series as a new column in the DataFra
   # result = grouped.apply(
    #print(f"The RGB values have dimension {rgb_diff_norm} which means they've been standardized so that \ntheir value only reflects a ratio. \n{rgb_diff_norm}")
        return rgb_diff_norm

In [30]:
import pandas as pd

data = {'Category': ['A', 'A', 'B', 'B'],
        'r': [255, 200, 100, 50],
        'g': [0, 50, 75, 100],
        'b': [0, 25, 50, 200]}

df = pd.DataFrame(data)

# Group by 'Category'
grouped = df.groupby('Category')

# Access the first row of each group for 'r', 'g', 'b'
rgb1 = grouped[['r', 'g', 'b']].first()

print(rgb1)

            r   g   b
Category
A         255   0   0
B         100  75  50

In [31]:
def rgb_diff(group):
    # Assuming you have sorted the DataFrame by stimulus
    rgb_values = group[['r', 'g', 'b']].values
    rgb1, rgb2, rgb3 = rgb_values[0], rgb_values[1], rgb_values[2]
    rgb_diff = abs(rgb1 - rgb2) + abs(rgb2 - rgb3) + abs(rgb3 - rgb1)

    return pd.Series(rgb_diff, index=['diff_r', 'diff_g', 'diff_b'])

# Group by 'stimulus' and apply the rgb_diff function
result = df.groupby('stimulus').apply(rgb_diff).reset_index()

#here's what the results look like. It has shape (stimulus, r_diff, g_diff, b_diff) of length 36
print(f"The shape of the dataset is: {result.shape} with length {result.shape[0]}")

result_norm = result[['diff_r', 'diff_g', 'diff_b']] / 255
test_score_rgb = result_norm.sum() / len(result)
final_test_score = test_score_rgb.sum()
print(f"the final score of the participant is: {final_test_score}")

KeyError: 'stimulus'

In [32]:
result

NameError: name 'result' is not defined