In [1]:
%pip install pandas
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.1.0)
Requirement already satisfied: numpy>=1.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
file_path = "grapheme-color-trials-2023-09-12-13-36-11.csv"
df = pd.read_csv(file_path)

In [3]:
#print(df.to_string())
#test change on the emil-dev branch
# Get the list of all column names from headers
column_headers = list(df.columns.values)
print("The Column Header :", column_headers)
df.info()

The Column Header : ['id', 'battery_id', 'start_r', 'start_g', 'start_b', 'r', 'g', 'b', 'datetimenow', 'inducer_id', 'stimulus', 'synesthesia_test_id', 'test_name', 'email']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   108 non-null    int64
 1   battery_id           108 non-null    int64
 2   start_r              108 non-null    int64
 3   start_g              108 non-null    int64
 4   start_b              108 non-null    int64
 5   r                    108 non-null    int64
 6   g                    108 non-null    int64
 7   b                    108 non-null    int64
 8   datetimenow          108 non-null    object
 9   inducer_id           108 non-null    int64
 10  stimulus             108 non-null    object
 11  synesthesia_test_id  108 non-null    int64
 12  test_name            108 non-null    object
 13  email                108 non-null    object
dtypes: int64(10), object(4)
memory usage: 11.9+ KB

In [3]:
rgb_test = df[['r', 'g', 'b', 'stimulus']]
rgb_vals = df[['r', 'g', 'b']]
df

,id,battery_id,start_r,start_g,start_b,r,g,b,datetimenow,inducer_id,stimulus,synesthesia_test_id,test_name,email
0,14214651,229126,231,237,212,231,237,212,2023-09-07 13:32:51,32,6,1444747,grapheme-color,jacobh.inquiries@gmail.com
1,14214652,229126,188,47,197,188,47,197,2023-09-07 13:32:52,25,Z,1444747,grapheme-color,jacobh.inquiries@gmail.com
2,14214653,229126,166,177,195,166,177,195,2023-09-07 13:32:52,1,B,1444747,grapheme-color,jacobh.inquiries@gmail.com
3,14214654,229126,208,73,24,208,73,24,2023-09-07 13:32:52,20,U,1444747,grapheme-color,jacobh.inquiries@gmail.com
4,14214655,229126,205,180,161,205,180,161,2023-09-07 13:32:52,29,3,1444747,grapheme-color,jacobh.inquiries@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,14214754,229126,158,165,120,158,165,120,2023-09-07 13:33:10,26,0,1444747,grapheme-color,jacobh.inquiries@gmail.com
104,14214755,229126,101,124,231,101,124,231,2023-09-07 13:33:10,22,W,1444747,grapheme-color,jacobh.inquiries@gmail.com
105,14214756,229126,137,46,131,137,46,131,2023-09-07 13:33:10,18,S,1444747,grapheme-color,jacobh.inquiries@gmail.com
106,14214757,229126,236,58,109,236,58,109,2023-09-07 13:33:10,26,0,1444747,grapheme-color,jacobh.inquiries@gmail.com
107,14214758,229126,73,242,181,73,242,181,2023-09-07 13:33:10,26,0,1444747,grapheme-color,jacobh.inquiries@gmail.com

In [6]:
stim_rgb = rgb_test.groupby('stimulus')

In [15]:
import pandas as pd

# Assuming you have a DataFrame named 'rgb_test' with a 'stimulus' column
# and you want to iterate over each unique 'stimulus' value

# Group the DataFrame by 'stimulus'
grouped = rgb_test.groupby('stimulus')
#grouped2 = rgb_vals.groupby('stimulus')
#print(grouped)

def rgb_calc_test(dataset)
# Iterate over each unique 'stimulus' value
    for stimulus_value, group_data in grouped:
        stim = grouped.get_group(stimulus_value)
       # print(stim)
    
        #print(group_data)
        
    
        rgb1 = stim.iloc[0]
        rgb2 = stim.iloc[1]
        rgb3 = stim.iloc[2]
        print(rgb1)
        rgb_diff = abs(rgb1 - rgb2) + abs(rgb2 - rgb3) + abs(rgb3 - rgb1)
        print(rgb_diff)
        
        print(f"Stimulus Value: {stimulus_value}")
        print(f"Mean Value: {mean_value}")

r           158
g           165
b           120
stimulus      0
Name: 103, dtype: object

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [103]:
import pandas as pd

#Sample DataFrame with 'stimulus', 'R', 'G', and 'B' columns
#stim must be string, ie letters
#takes in (3,3) RGB values for each stimulus
#gives back (3,) rgb values for each stimulus (A-Z, 0-9)
def total_rgb_value(test_participant_name, stim):
# Group by 'stimulus'
    grouped = rgb_test.groupby(stim)

#measures the difference in RGB values
    for stimulus_value, group_data in grouped:
        stim = grouped.get_group(stimulus_value)


        # Select only the RGB columns for calculations
        rgb_data = stim[['r', 'g', 'b']]

        # Calculate RGB differences
        rgb_diff = abs(rgb_data.iloc[0] - rgb_data.iloc[1]) + abs(rgb_data.iloc[1] - rgb_data.iloc[2]) + abs(rgb_data.iloc[2] - rgb_data.iloc[0])
        
        #the value is also divided by 255 to normalize the data. (it reflects a ratio between RGB values)
        rgb_diff_norm = rgb_diff / 255
        
   # print(f"stimulus value: {stimulus_value} \n group data: {group_data}\n grouped: {grouped} \n rgb diff: {rgb_diff}")
    # Add the new Series as a new column in the DataFra
   # result = grouped.apply(
    #print(f"The RGB values have dimension {rgb_diff_norm} which means they've been standardized so that \ntheir value only reflects a ratio. \n{rgb_diff_norm}")
    return rgb_diff_norm

In [107]:
total_participant_name = 'sub_02_score'
stim = 'stimulus'
total_column = total_rgb_value(total_participant_name, stim)
#print(total_column)
#pd.Series([total_column], name=total_participant_name)
#df['sub_02_score']
result = grouped.apply(total_rgb_value(total_participant_name, stim))
print(total_column)

r    326
g    368
b    144
dtype: int64
r    1.278431
g    1.443137
b    0.564706
dtype: float64
r    278
g    396
b    276
dtype: int64
r    1.090196
g    1.552941
b    1.082353
dtype: float64
r    272
g     78
b    380
dtype: int64
r    1.066667
g    0.305882
b    1.490196
dtype: float64
r     44
g    302
b    324
dtype: int64
r    0.172549
g    1.184314
b    1.270588
dtype: float64
r    206
g    196
b    192
dtype: int64
r    0.807843
g    0.768627
b    0.752941
dtype: float64
r    106
g    238
b     74
dtype: int64
r    0.415686
g    0.933333
b    0.290196
dtype: float64
r    304
g    238
b    100
dtype: int64
r    1.192157
g    0.933333
b    0.392157
dtype: float64
r    292
g    318
b    188
dtype: int64
r    1.145098
g    1.247059
b    0.737255
dtype: float64
r    250
g    470
b    242
dtype: int64
r    0.980392
g    1.843137
b    0.949020
dtype: float64
r    360
g    160
b    212
dtype: int64
r    1.411765
g    0.627451
b    0.831373
dtype: float64
r    382
g    312
b    306
dtype: int64
r    1.498039
g    1.223529
b    1.200000
dtype: float64
r    288
g    170
b    310
dtype: int64
r    1.129412
g    0.666667
b    1.215686
dtype: float64
r    160
g    358
b    126
dtype: int64
r    0.627451
g    1.403922
b    0.494118
dtype: float64
r     38
g     72
b    278
dtype: int64
r    0.149020
g    0.282353
b    1.090196
dtype: float64
r    372
g    388
b    158
dtype: int64
r    1.458824
g    1.521569
b    0.619608
dtype: float64
r    136
g    118
b    382
dtype: int64
r    0.533333
g    0.462745
b    1.498039
dtype: float64
r    124
g    226
b    346
dtype: int64
r    0.486275
g    0.886275
b    1.356863
dtype: float64
r    284
g    140
b    302
dtype: int64
r    1.113725
g    0.549020
b    1.184314
dtype: float64
r     50
g     62
b    340
dtype: int64
r    0.196078
g    0.243137
b    1.333333
dtype: float64
r    122
g     96
b    412
dtype: int64
r    0.478431
g    0.376471
b    1.615686
dtype: float64
r    338
g    142
b    346
dtype: int64
r    1.325490
g    0.556863
b    1.356863
dtype: float64
r    172
g    104
b    144
dtype: int64
r    0.674510
g    0.407843
b    0.564706
dtype: float64
r    234
g    184
b    222
dtype: int64
r    0.917647
g    0.721569
b    0.870588
dtype: float64
r     64
g    256
b    256
dtype: int64
r    0.250980
g    1.003922
b    1.003922
dtype: float64
r    284
g    398
b    194
dtype: int64
r    1.113725
g    1.560784
b    0.760784
dtype: float64
r    308
g    318
b    302
dtype: int64
r    1.207843
g    1.247059
b    1.184314
dtype: float64
r    382
g    430
b    322
dtype: int64
r    1.498039
g    1.686275
b    1.262745
dtype: float64
r    202
g    176
b    452
dtype: int64
r    0.792157
g    0.690196
b    1.772549
dtype: float64
r    432
g    328
b    214
dtype: int64
r    1.694118
g    1.286275
b    0.839216
dtype: float64
r    144
g    384
b    170
dtype: int64
r    0.564706
g    1.505882
b    0.666667
dtype: float64
r    404
g    216
b    204
dtype: int64
r    1.584314
g    0.847059
b    0.800000
dtype: float64
r    474
g    420
b    132
dtype: int64
r    1.858824
g    1.647059
b    0.517647
dtype: float64
r    130
g    182
b    332
dtype: int64
r    0.509804
g    0.713725
b    1.301961
dtype: float64
r    210
g    170
b    478
dtype: int64
r    0.823529
g    0.666667
b    1.874510
dtype: float64
r     30
g    362
b    408
dtype: int64
r    0.117647
g    1.419608
b    1.600000
dtype: float64
r    142
g    238
b    202
dtype: int64
r    0.556863
g    0.933333
b    0.792157
dtype: float64
r    326
g    368
b    144
dtype: int64
r    1.278431
g    1.443137
b    0.564706
dtype: float64
r    278
g    396
b    276
dtype: int64
r    1.090196
g    1.552941
b    1.082353
dtype: float64
r    272
g     78
b    380
dtype: int64
r    1.066667
g    0.305882
b    1.490196
dtype: float64
r     44
g    302
b    324
dtype: int64
r    0.172549
g    1.184314
b    1.270588
dtype: float64
r    206
g    196
b    192
dtype: int64
r    0.807843
g    0.768627
b    0.752941
dtype: float64
r    106
g    238
b     74
dtype: int64
r    0.415686
g    0.933333
b    0.290196
dtype: float64
r    304
g    238
b    100
dtype: int64
r    1.192157
g    0.933333
b    0.392157
dtype: float64
r    292
g    318
b    188
dtype: int64
r    1.145098
g    1.247059
b    0.737255
dtype: float64
r    250
g    470
b    242
dtype: int64
r    0.980392
g    1.843137
b    0.949020
dtype: float64
r    360
g    160
b    212
dtype: int64
r    1.411765
g    0.627451
b    0.831373
dtype: float64
r    382
g    312
b    306
dtype: int64
r    1.498039
g    1.223529
b    1.200000
dtype: float64
r    288
g    170
b    310
dtype: int64
r    1.129412
g    0.666667
b    1.215686
dtype: float64
r    160
g    358
b    126
dtype: int64
r    0.627451
g    1.403922
b    0.494118
dtype: float64
r     38
g     72
b    278
dtype: int64
r    0.149020
g    0.282353
b    1.090196
dtype: float64
r    372
g    388
b    158
dtype: int64
r    1.458824
g    1.521569
b    0.619608
dtype: float64
r    136
g    118
b    382
dtype: int64
r    0.533333
g    0.462745
b    1.498039
dtype: float64
r    124
g    226
b    346
dtype: int64
r    0.486275
g    0.886275
b    1.356863
dtype: float64
r    284
g    140
b    302
dtype: int64
r    1.113725
g    0.549020
b    1.184314
dtype: float64
r     50
g     62
b    340
dtype: int64
r    0.196078
g    0.243137
b    1.333333
dtype: float64
r    122
g     96
b    412
dtype: int64
r    0.478431
g    0.376471
b    1.615686
dtype: float64
r    338
g    142
b    346
dtype: int64
r    1.325490
g    0.556863
b    1.356863
dtype: float64
r    172
g    104
b    144
dtype: int64
r    0.674510
g    0.407843
b    0.564706
dtype: float64
r    234
g    184
b    222
dtype: int64
r    0.917647
g    0.721569
b    0.870588
dtype: float64
r     64
g    256
b    256
dtype: int64
r    0.250980
g    1.003922
b    1.003922
dtype: float64
r    284
g    398
b    194
dtype: int64
r    1.113725
g    1.560784
b    0.760784
dtype: float64
r    308
g    318
b    302
dtype: int64
r    1.207843
g    1.247059
b    1.184314
dtype: float64
r    382
g    430
b    322
dtype: int64
r    1.498039
g    1.686275
b    1.262745
dtype: float64
r    202
g    176
b    452
dtype: int64
r    0.792157
g    0.690196
b    1.772549
dtype: float64
r    432
g    328
b    214
dtype: int64
r    1.694118
g    1.286275
b    0.839216
dtype: float64
r    144
g    384
b    170
dtype: int64
r    0.564706
g    1.505882
b    0.666667
dtype: float64
r    404
g    216
b    204
dtype: int64
r    1.584314
g    0.847059
b    0.800000
dtype: float64
r    474
g    420
b    132
dtype: int64
r    1.858824
g    1.647059
b    0.517647
dtype: float64
r    130
g    182
b    332
dtype: int64
r    0.509804
g    0.713725
b    1.301961
dtype: float64
r    210
g    170
b    478
dtype: int64
r    0.823529
g    0.666667
b    1.874510
dtype: float64
r     30
g    362
b    408
dtype: int64
r    0.117647
g    1.419608
b    1.600000
dtype: float64
r    142
g    238
b    202
dtype: int64
r    0.556863
g    0.933333
b    0.792157
dtype: float64

TypeError: unhashable type: 'Series'

In [143]:
rgb_test = df[['r', 'g', 'b', 'stimulus', 'sub_02_score']]
stim_rgb = rgb_test.groupby('stimulus')
stim_rgb.get_group('0')

       r    g    b stimulus sub_02_score
103  158  165  120        0          NaN
106  236   58  109        0          NaN
107   73  242  181        0          NaN